import { defineWidget, TOOLBOX_CATEGORIES, type WidgetCatalogItem } from "./types";

export const CANONICAL_WIDGET_IDS = [
  "PRIM-RECT",
  "AST-IMAGE",
  "IND-STATE",
  "CMD-BUTTON",
  "INP-NUMERIC",
  "IND-VALUE",
  "VIS-TREND",
  "UTIL-QRCODE",
  "INP-BOOLEAN",
  "INP-SELECT",
  "LAY-DISCLOSURE",
  "DATA-COLLECTION",
  "OVL-DIALOG",
  "INP-TEXT",
  "NAV-LINK",
  "NAV-TABS",
  "VIS-TIMELINE",
  "IND-METER",
  "FDBK-NOTIFICATION",
  "NAV-MENU",
  "FDBK-TOOLTIP",
  "NAV-EMBED",
  "ALM-PANEL",
  "PRIM-TEXT",
  "PRIM-CONNECTOR",
  "LAY-PANEL",
  "AST-SYMBOL",
  "PROC-SYMBOL",
  "PROC-FACEPLATE",
  "ALM-BANNER",
  "ALM-INDICATOR",
  "IND-DATASTATUS",
  "INP-DATETIME-RANGE",
  "NAV-BREADCRUMB",
  "DATA-EVENTLOG",
] as const;

export type CanonicalWidgetId = (typeof CANONICAL_WIDGET_IDS)[number];

const canonicalWidgets: WidgetCatalogItem[] = [
  defineWidget({
    canonicalId: "PRIM-TEXT",
    type: "label",
    label: "Tekst / Label",
    description: "Lokalizowany tekst, nagłówek lub podpis wartości.",
    category: "Prymitywy",
    icon: "T",
    defaultW: 180,
    defaultH: 32,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "LOC", "A11Y", "TME", "ANIM"],
    aliases: ["Label"],
    defaultConfig: {
      text: "Label",
      fontTokenId: "font-label",
      fontFamily: "Segoe UI, system-ui, sans-serif",
      fontSize: 14,
      fontWeight: "normal",
      fontStyle: "normal",
      textColor: "#1f2937",
      bgColor: "transparent",
      borderColor: "transparent",
      borderWidth: 0,
      borderRadius: 0,
      align: "left",
      vAlign: "center",
    },
  }),
  defineWidget({
    canonicalId: "PRIM-RECT",
    type: "shape",
    label: "Prostokąt / Shape",
    description: "Tło, obszar procesu i prosty kształt stanowy.",
    category: "Prymitywy",
    icon: "▢",
    defaultW: 180,
    defaultH: 120,
    capabilities: ["BASE", "GEO", "LAY", "TME", "ANIM"],
    aliases: ["Prostokąt"],
    defaultConfig: {
      title: "",
      borderRadius: 10,
      bgColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderStyle: "solid",
    },
  }),
  defineWidget({
    canonicalId: "PRIM-CONNECTOR",
    type: "line",
    label: "Linia / Łącznik",
    description: "Linia, rurociąg lub kierunkowe połączenie procesu.",
    category: "Prymitywy",
    icon: "／",
    defaultW: 200,
    defaultH: 80,
    capabilities: ["BASE", "GEO", "LAY", "DAT", "QTY", "STA", "TME", "ANIM"],
    aliases: ["Line / Arrow"],
    defaultConfig: {
      x1: 8,
      y1: 50,
      x2: 92,
      y2: 50,
      stroke: "#1f2937",
      strokeWidth: 2.5,
      lineStyle: "solid",
      startCap: "none",
      endCap: "arrow",
      capSize: 12,
    },
  }),
  defineWidget({
    canonicalId: "AST-IMAGE",
    type: "image",
    label: "Obraz / Ikona",
    description: "Lokalny obraz statyczny lub mapowany do stanu.",
    category: "Zasoby",
    icon: "▧",
    defaultW: 120,
    defaultH: 120,
    capabilities: ["BASE", "GEO", "AST", "DAT", "QTY", "TME", "ANIM"],
    aliases: ["Obraz"],
    defaultConfig: {
      src: "",
      fit: "contain",
      alt: "Process image",
      borderRadius: 0,
      bgColor: "transparent",
      borderColor: "transparent",
      borderWidth: 0,
      borderStyle: "none",
    },
  }),
  defineWidget({
    canonicalId: "AST-SYMBOL",
    type: "vector_symbol",
    label: "Symbol wektorowy",
    description: "Bezpieczny, lokalny symbol SVG z mapowaniem stanu.",
    category: "Zasoby",
    icon: "◇",
    defaultW: 150,
    defaultH: 130,
    capabilities: ["BASE", "GEO", "AST", "DAT", "QTY", "STA", "TME", "ANIM", "A11Y"],
    defaultConfig: {
      symbol: "pump",
      label: "VECTOR SYMBOL",
      activeColor: "#2563eb",
      idleColor: "#64748b",
    },
  }),
  defineWidget({
    canonicalId: "IND-STATE",
    type: "state_indicator",
    label: "Wskaźnik stanu",
    description: "Bit Lamp i WordLamp jako warianty jednego kontraktu.",
    category: "Wskaźniki",
    icon: "●",
    defaultW: 190,
    defaultH: 52,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "STA", "TME", "A11Y", "ANIM"],
    aliases: ["Bit Lamp", "WordLamp", "lamp", "bool_display"],
    defaultConfig: {
      variant: "bit",
      title: "STATE",
      bitIndex: 0,
      states: "0|OFF|#64748b|○\n1|ON|#16a34a|●",
      unknownLabel: "UNKNOWN",
    },
  }),
  defineWidget({
    canonicalId: "IND-VALUE",
    type: "numeric",
    label: "Wartość numeryczna",
    description: "Wartość procesowa z jednostką, precyzją, jakością i czasem.",
    category: "Wskaźniki",
    icon: "#",
    defaultW: 160,
    defaultH: 56,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "STA", "TME", "A11Y"],
    aliases: ["Display register"],
    defaultConfig: {
      title: "VALUE",
      fontTokenId: "font-value",
      decimals: 0,
      unit: "",
      bgColor: "#ffffff",
      textColor: "#1f2937",
    },
  }),
  defineWidget({
    canonicalId: "IND-METER",
    type: "meter",
    label: "Miernik",
    description: "Bar graph, progress lub gauge z progami.",
    category: "Wskaźniki",
    icon: "◒",
    defaultW: 220,
    defaultH: 90,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "STA", "TME", "A11Y", "ANIM"],
    aliases: ["BarGraph", "Progress"],
    defaultConfig: {
      variant: "bar",
      title: "METER",
      min: 0,
      max: 100,
      value: 65,
      unit: "%",
      decimals: 0,
      warningAt: 75,
      alarmAt: 90,
      fillColor: "#2563eb",
    },
  }),
  defineWidget({
    canonicalId: "IND-DATASTATUS",
    type: "data_status",
    label: "Status danych",
    description: "Live, simulation, stale, bad quality i disconnected.",
    category: "Wskaźniki",
    icon: "◉",
    defaultW: 190,
    defaultH: 58,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "STA", "A11Y", "TME"],
    defaultConfig: { environment: "LIVE", staleAfterMs: 2000 },
  }),
  defineWidget({
    canonicalId: "PROC-SYMBOL",
    type: "process_symbol",
    label: "Symbol procesu",
    description: "Pompa, zawór, silnik, zbiornik lub czujnik w standardzie HMI.",
    category: "Wizualizacja procesu",
    icon: "⚙",
    defaultW: 190,
    defaultH: 150,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "STA", "ALM", "AST", "TME", "ANIM", "A11Y"],
    defaultConfig: {
      variant: "pump",
      label: "PUMP 1",
      runningColor: "#2563eb",
      idleColor: "#64748b",
      fault: false,
      local: false,
    },
  }),
  defineWidget({
    canonicalId: "PROC-FACEPLATE",
    type: "faceplate",
    label: "Faceplate obiektu",
    description: "Status, jakość, permissive, alarmy i dozwolone komendy obiektu.",
    category: "Wizualizacja procesu",
    icon: "▣",
    defaultW: 300,
    defaultH: 260,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "STA", "ALM", "CMD", "WR", "PERM", "NAV", "OVL", "A11Y", "TME"],
    defaultConfig: {
      variant: "detail",
      equipmentName: "PUMP 1",
      mode: "AUTO",
      available: true,
      permissive: true,
      local: false,
      unit: "",
      startTagId: "",
      stopTagId: "",
      startValue: 1,
      stopValue: 1,
      alarmSummary: "No active alarms",
    },
  }),
  defineWidget({
    canonicalId: "CMD-BUTTON",
    type: "command_button",
    label: "Przycisk komendy",
    description: "Set, reset, toggle, momentary, value lub typed action.",
    category: "Sterowanie",
    icon: "▶",
    defaultW: 170,
    defaultH: 48,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "CMD", "WR", "PERM", "VAL", "A11Y", "TME"],
    aliases: ["Set Bit button", "Set Rejgister button", "Set Register Button", "Function button", "write_button"],
    defaultConfig: {
      mode: "set",
      label: "COMMAND",
      writeValue: 1,
      confirm: true,
      confirmText: "Send command?",
      disabledWhenBad: true,
      pendingLabel: "COMMAND SENT",
      watchdogConfigured: false,
    },
  }),
  defineWidget({
    canonicalId: "INP-NUMERIC",
    type: "numeric_input",
    label: "Wejście numeryczne",
    description: "Field, slider lub stepper z walidacją i kontrolowanym zapisem.",
    category: "Wejścia",
    icon: "↕",
    defaultW: 220,
    defaultH: 82,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "INP", "VAL", "WR", "PERM", "A11Y", "TME"],
    aliases: ["Suwak"],
    defaultConfig: {
      variant: "stepper",
      title: "SETPOINT",
      min: 0,
      max: 100,
      step: 1,
      unit: "",
      decimals: 0,
      commitMode: "change",
      defaultValue: 50,
    },
  }),
  defineWidget({
    canonicalId: "INP-BOOLEAN",
    type: "boolean_input",
    label: "Wejście logiczne",
    description: "Checkbox lub switch z jawnym wynikiem zapisu.",
    category: "Wejścia",
    icon: "◩",
    defaultW: 190,
    defaultH: 54,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "INP", "VAL", "WR", "PERM", "A11Y", "TME"],
    aliases: ["CheckBox", "Switch"],
    defaultConfig: {
      variant: "switch",
      label: "BOOLEAN",
      trueLabel: "ON",
      falseLabel: "OFF",
      confirm: false,
      disabledWhenBad: true,
    },
  }),
  defineWidget({
    canonicalId: "INP-SELECT",
    type: "select_input",
    label: "Wybór z listy",
    description: "Select lub chips z mapowaniem value:label.",
    category: "Wejścia",
    icon: "▾",
    defaultW: 220,
    defaultH: 80,
    capabilities: ["BASE", "GEO", "DAT", "INP", "SEL", "VAL", "A11Y", "TME"],
    aliases: ["ComboBox", "Chips"],
    defaultConfig: {
      variant: "select",
      label: "SELECT",
      options: "0:OFF,1:AUTO,2:MANUAL",
      selectedValue: "0",
    },
  }),
  defineWidget({
    canonicalId: "INP-TEXT",
    type: "text_input",
    label: "Pole tekstowe",
    description: "Tekst lub liczba z walidacją, commit i cancel.",
    category: "Wejścia",
    icon: "Ab",
    defaultW: 230,
    defaultH: 84,
    capabilities: ["BASE", "GEO", "DAT", "INP", "VAL", "A11Y", "TME"],
    aliases: ["TextField"],
    defaultConfig: {
      variant: "text",
      label: "TEXT",
      placeholder: "Enter value",
      maxLength: 64,
      pattern: "",
      value: "",
    },
  }),
  defineWidget({
    canonicalId: "INP-DATETIME-RANGE",
    type: "datetime_range",
    label: "Zakres daty i czasu",
    description: "Absolute lub relative time range dla trendów i historii.",
    category: "Wejścia",
    icon: "◷",
    defaultW: 300,
    defaultH: 110,
    capabilities: ["BASE", "GEO", "INP", "VAL", "HIS", "LOC", "A11Y", "TME"],
    defaultConfig: {
      mode: "relative",
      title: "TIME RANGE",
      relative: "1h",
      timezone: "Local",
    },
  }),
  defineWidget({
    canonicalId: "VIS-TREND",
    type: "trend",
    label: "Trend czasowy",
    description: "Lekki trend live/history z quality gaps.",
    category: "Dane i historia",
    icon: "⌁",
    defaultW: 360,
    defaultH: 220,
    capabilities: ["BASE", "GEO", "DAT", "HIS", "QTY", "TME", "A11Y"],
    aliases: ["Chart"],
    defaultConfig: {
      title: "TREND",
      seriesLabel: "PV",
      points: "12,18,15,28,36,32,48,55,51,68",
      min: 0,
      max: 100,
      unit: "",
      liveAppend: true,
    },
  }),
  defineWidget({
    canonicalId: "DATA-COLLECTION",
    type: "collection_view",
    label: "Widok kolekcji",
    description: "List, table lub grid dla danych online i historycznych.",
    category: "Dane i historia",
    icon: "▤",
    defaultW: 380,
    defaultH: 230,
    capabilities: ["BASE", "GEO", "DAT", "QTY", "COL", "VIR", "HIS", "SEL", "A11Y", "TME"],
    aliases: ["DataGrid", "List", "Simple table"],
    defaultConfig: {
      variant: "table",
      title: "COLLECTION",
      columns: "name,value,status",
      pageSize: 5,
      selectable: true,
      rows: '[{"name":"Pump 1","value":42,"status":"RUN"},{"name":"Pump 2","value":0,"status":"STOP"}]',
    },
  }),
  defineWidget({
    canonicalId: "VIS-TIMELINE",
    type: "event_timeline",
    label: "Oś zdarzeń",
    description: "Chronologiczna prezentacja alarmów, zdarzeń i partii.",
    category: "Dane i historia",
    icon: "⋮",
    defaultW: 340,
    defaultH: 220,
    capabilities: ["BASE", "GEO", "HIS", "DAT", "TME", "A11Y"],
    aliases: ["TimeLine", "Timeline"],
    defaultConfig: {
      title: "EVENT TIMELINE",
      severityFilter: "all",
      events: '[{"time":"12:00:01","title":"Pump started","detail":"P1","severity":"info"},{"time":"12:03:18","title":"High level","detail":"Wet well","severity":"warning"}]',
    },
  }),
  defineWidget({
    canonicalId: "DATA-EVENTLOG",
    type: "event_audit_viewer",
    label: "Zdarzenia i audyt",
    description: "Filtrowalny, niemodyfikowalny widok zdarzeń i audytu.",
    category: "Dane i historia",
    icon: "☷",
    defaultW: 420,
    defaultH: 240,
    capabilities: ["BASE", "GEO", "DAT", "COL", "VIR", "HIS", "PERM", "A11Y", "TME"],
    defaultConfig: {
      title: "EVENT / AUDIT",
      pageSize: 6,
      rows: '[{"time":"12:10:01","actor":"operator","action":"START P1","result":"verified","correlationId":"cmd-001"}]',
    },
  }),
  defineWidget({
    canonicalId: "LAY-PANEL",
    type: "panel",
    label: "Panel / Kontener",
    description: "Semantyczne grupowanie elementów i układu.",
    category: "Układ",
    icon: "▭",
    defaultW: 260,
    defaultH: 180,
    capabilities: ["BASE", "GEO", "LAY", "A11Y", "TME"],
    aliases: ["Group Panel"],
    defaultConfig: {
      title: "PANEL",
      bgColor: "#ffffff",
      borderColor: "#cbd5e1",
    },
  }),
  defineWidget({
    canonicalId: "LAY-DISCLOSURE",
    type: "disclosure_panel",
    label: "Panel zwijany",
    description: "Dostępny, zwijany fragment ekranu.",
    category: "Układ",
    icon: "▾",
    defaultW: 260,
    defaultH: 150,
    capabilities: ["BASE", "GEO", "LAY", "A11Y", "TME"],
    aliases: ["Collapse"],
    defaultConfig: {
      title: "DISCLOSURE",
      content: "Grouped screen content",
      expanded: true,
    },
  }),
  defineWidget({
    canonicalId: "NAV-LINK",
    type: "navigation_link",
    label: "Łącze nawigacyjne",
    description: "Bezpieczne przejście do ekranu lub trasy wewnętrznej.",
    category: "Nawigacja",
    icon: "↗",
    defaultW: 180,
    defaultH: 42,
    capabilities: ["BASE", "GEO", "NAV", "PERM", "A11Y", "TME"],
    aliases: ["Link"],
    defaultConfig: { label: "OPEN SCREEN", target: "screen:Main", params: "{}" },
  }),
  defineWidget({
    canonicalId: "NAV-TABS",
    type: "tab_set",
    label: "Zakładki",
    description: "Sekcje ekranu z obsługą klawiatury.",
    category: "Nawigacja",
    icon: "▰",
    defaultW: 340,
    defaultH: 180,
    capabilities: ["BASE", "GEO", "NAV", "LAY", "PERM", "A11Y", "TME"],
    aliases: ["Tabs"],
    defaultConfig: { tabs: "Overview,Process,Alarms,Maintenance", activeIndex: 0 },
  }),
  defineWidget({
    canonicalId: "NAV-MENU",
    type: "navigation_menu",
    label: "Menu nawigacyjne",
    description: "Hierarchiczne menu ekranów zależne od uprawnień.",
    category: "Nawigacja",
    icon: "☰",
    defaultW: 220,
    defaultH: 230,
    capabilities: ["BASE", "GEO", "NAV", "PERM", "ALM", "A11Y", "TME"],
    aliases: ["NavMenu"],
    defaultConfig: {
      title: "NAVIGATION",
      items: "Overview=screen:Overview\nPumping/Pump stations=screen:Pumps\nAlarms=screen:Alarms",
    },
  }),
  defineWidget({
    canonicalId: "NAV-EMBED",
    type: "embedded_screen",
    label: "Osadzony ekran",
    description: "Ekran lub faceplate z parametrami i izolacją kontekstu.",
    category: "Nawigacja",
    icon: "▣",
    defaultW: 320,
    defaultH: 240,
    capabilities: ["BASE", "GEO", "NAV", "DAT", "PERM", "LAY", "QTY", "A11Y", "TME"],
    aliases: ["Embeded screen", "Embedded Screen"],
    defaultConfig: {
      target_form_id: "",
      tag_prefix: "",
      tag_overrides: {},
      scale_mode: "fit",
      bgColor: "transparent",
      borderColor: "#94a3b8",
      borderWidth: 1,
      borderStyle: "dashed",
    },
  }),
  defineWidget({
    canonicalId: "NAV-BREADCRUMB",
    type: "breadcrumb",
    label: "Ścieżka nawigacji",
    description: "Pozycja w hierarchii zakładu, obiektu i ekranu.",
    category: "Nawigacja",
    icon: "›",
    defaultW: 320,
    defaultH: 40,
    capabilities: ["BASE", "GEO", "NAV", "PERM", "A11Y", "TME"],
    defaultConfig: { path: "Zakład A/Pompownie/PS_001/Detail" },
  }),
  defineWidget({
    canonicalId: "OVL-DIALOG",
    type: "dialog",
    label: "Dialog",
    description: "Modalny, niemodalny lub confirmation preview.",
    category: "Informacja i interakcja",
    icon: "□",
    defaultW: 300,
    defaultH: 180,
    capabilities: ["BASE", "GEO", "OVL", "VAL", "PERM", "A11Y", "TME"],
    aliases: ["Dialog", "MessageBox"],
    defaultConfig: {
      variant: "confirmation",
      title: "CONFIRM ACTION",
      message: "Review the action before continuing.",
      confirmLabel: "Confirm",
      cancelLabel: "Cancel",
      modal: true,
    },
  }),
  defineWidget({
    canonicalId: "FDBK-NOTIFICATION",
    type: "notification",
    label: "Powiadomienie",
    description: "Inline alert albo toast dla niekrytycznego feedbacku.",
    category: "Informacja i interakcja",
    icon: "!",
    defaultW: 300,
    defaultH: 82,
    capabilities: ["BASE", "GEO", "DAT", "STA", "A11Y", "TME"],
    aliases: ["Alert", "Snackbar"],
    defaultConfig: {
      variant: "inline",
      severity: "info",
      title: "INFORMATION",
      message: "Operation status or guidance.",
      dismissible: true,
    },
  }),
  defineWidget({
    canonicalId: "FDBK-TOOLTIP",
    type: "tooltip",
    label: "Podpowiedź",
    description: "Pomoc, wartość i diagnostyka dostępna także klawiaturą.",
    category: "Informacja i interakcja",
    icon: "?",
    defaultW: 230,
    defaultH: 100,
    capabilities: ["BASE", "GEO", "A11Y", "DAT", "QTY", "TME"],
    aliases: ["Tooltip"],
    defaultConfig: {
      variant: "help",
      title: "CONTEXT HELP",
      text: "Explain the control, engineering unit and operator action.",
      showAge: true,
    },
  }),
  defineWidget({
    canonicalId: "ALM-PANEL",
    type: "alarm_panel",
    label: "Panel alarmów",
    description: "Aktywne/historyczne alarmy, filtry i żądania ACK.",
    category: "Alarmy",
    icon: "♟",
    defaultW: 430,
    defaultH: 260,
    capabilities: ["BASE", "GEO", "ALM", "COL", "VIR", "HIS", "PERM", "A11Y", "TME"],
    aliases: ["Alarm Panel"],
    defaultConfig: { title: "ALARMS", stateFilter: "all", priorityFilter: "all", groupFilter: "" },
  }),
  defineWidget({
    canonicalId: "ALM-BANNER",
    type: "alarm_banner",
    label: "Banner alarmowy",
    description: "Najwyższy niepotwierdzony alarm i licznik.",
    category: "Alarmy",
    icon: "▲",
    defaultW: 420,
    defaultH: 66,
    capabilities: ["BASE", "GEO", "ALM", "A11Y", "NAV", "TME"],
    defaultConfig: { title: "HIGHEST UNACKNOWLEDGED", alarms: "[]" },
  }),
  defineWidget({
    canonicalId: "ALM-INDICATOR",
    type: "alarm_indicator",
    label: "Wskaźnik alarmu",
    description: "Roll-up grupy przez ikonę, tekst, wzór i licznik.",
    category: "Alarmy",
    icon: "△",
    defaultW: 190,
    defaultH: 68,
    capabilities: ["BASE", "GEO", "ALM", "QTY", "A11Y", "NAV", "TME", "ANIM"],
    defaultConfig: { group: "Plant/Area/Object", alarms: "[]" },
  }),
  defineWidget({
    canonicalId: "UTIL-QRCODE",
    type: "qr_code",
    label: "Kod QR",
    description: "Lokalnie generowany kod QR z wartości statycznej lub taga.",
    category: "Narzędzia",
    icon: "▦",
    defaultW: 150,
    defaultH: 170,
    capabilities: ["BASE", "GEO", "DAT", "VAL", "A11Y"],
    aliases: ["QRCode"],
    defaultConfig: {
      source: "static",
      text: "ProSCADA",
      caption: "QR CODE",
      errorCorrection: "M",
      margin: 2,
    },
  }),
];

const processTemplates: WidgetCatalogItem[] = [
  defineWidget({
    canonicalId: "TPL-TANK-LEVEL",
    type: "tank",
    label: "2D Tank Level",
    description: "Legacy template poziomu zbiornika.",
    category: "Szablony procesu",
    icon: "▣",
    defaultW: 120,
    defaultH: 220,
    capabilities: ["DAT", "QTY", "STA"],
    status: "template",
    defaultConfig: { title: "LEVEL", min: 0, max: 1000, unit: "cm", fillColor: "#39b7e6", warn: 700, alarm: 850, showValue: true, bgColor: "#ffffff" },
  }),
  defineWidget({
    canonicalId: "TPL-BAR",
    type: "bar",
    label: "Legacy Bar Graph",
    description: "Legacy bar retained for project compatibility.",
    category: "Szablony procesu",
    icon: "▬",
    defaultW: 200,
    defaultH: 40,
    capabilities: ["DAT", "QTY"],
    status: "template",
    defaultConfig: { title: "BAR", min: 0, max: 100, fillColor: "#16a34a", bgColor: "#ffffff" },
  }),
  defineWidget({
    canonicalId: "TPL-WATER-TANK",
    type: "iso_water_tank",
    label: "Iso Water Tank",
    description: "Izometryczny zbiornik dla demonstratora Water Tank.",
    category: "Szablony procesu",
    icon: "◫",
    defaultW: 360,
    defaultH: 300,
    capabilities: ["DAT", "QTY", "STA"],
    status: "template",
    defaultConfig: { label: "Water Tank Cutaway" },
  }),
  defineWidget({
    canonicalId: "TPL-PUMP",
    type: "iso_pump",
    label: "Iso Pump",
    description: "Izometryczna pompa demonstratora.",
    category: "Szablony procesu",
    icon: "⚙",
    defaultW: 160,
    defaultH: 140,
    capabilities: ["DAT", "QTY", "STA"],
    status: "template",
    defaultConfig: { pumpName: "PUMP 1" },
  }),
  defineWidget({
    canonicalId: "TPL-PIPE",
    type: "iso_pipe",
    label: "Iso Pipe Segment",
    description: "Izometryczny segment rurociągu.",
    category: "Szablony procesu",
    icon: "═",
    defaultW: 260,
    defaultH: 70,
    capabilities: ["DAT", "STA"],
    status: "template",
    defaultConfig: { label: "Inlet Pipe" },
  }),
  defineWidget({
    canonicalId: "TPL-TERRAIN",
    type: "iso_terrain",
    label: "Iso Terrain Cutaway",
    description: "Izometryczny przekrój terenu.",
    category: "Szablony procesu",
    icon: "▰",
    defaultW: 400,
    defaultH: 180,
    capabilities: ["STA"],
    status: "template",
    defaultConfig: { label: "Soil & Grass Cutaway" },
  }),
  defineWidget({
    canonicalId: "TPL-SETPOINTS",
    type: "setpoint_control",
    label: "Setpoints Controller",
    description: "Złożony kontroler setpointów demonstratora.",
    category: "Szablony procesu",
    icon: "≡",
    defaultW: 280,
    defaultH: 230,
    capabilities: ["DAT", "CMD", "WR"],
    status: "template",
    defaultConfig: { title: "Setpoints" },
  }),
  defineWidget({
    canonicalId: "TPL-INFLOW",
    type: "inflow_control",
    label: "Inflow K Controller",
    description: "Złożony kontroler współczynnika dopływu.",
    category: "Szablony procesu",
    icon: "K",
    defaultW: 240,
    defaultH: 120,
    capabilities: ["DAT", "CMD", "WR"],
    status: "template",
    defaultConfig: { title: "Inflow K" },
  }),
  defineWidget({
    canonicalId: "TPL-FREEZE",
    type: "process_control",
    label: "Process Freeze Controller",
    description: "Kontroler freeze/resume demonstratora.",
    category: "Szablony procesu",
    icon: "Ⅱ",
    defaultW: 260,
    defaultH: 120,
    capabilities: ["DAT", "CMD", "WR"],
    status: "template",
    defaultConfig: { title: "Process Freeze" },
  }),
  defineWidget({
    canonicalId: "TPL-METRICS",
    type: "metrics_panel",
    label: "Metrics Overview Bar",
    description: "Złożony pasek KPI demonstratora.",
    category: "Szablony procesu",
    icon: "▥",
    defaultW: 600,
    defaultH: 80,
    capabilities: ["DAT", "QTY", "STA"],
    status: "template",
    defaultConfig: { title: "Metrics Overview" },
  }),
];

export const WIDGET_CATALOG = [...canonicalWidgets, ...processTemplates];
export const CANONICAL_WIDGETS = WIDGET_CATALOG.filter((item) => item.status !== "template");
export const TEMPLATE_WIDGETS = WIDGET_CATALOG.filter((item) => item.status === "template");
export const WIDGET_CATALOG_BY_TYPE = new Map(WIDGET_CATALOG.map((item) => [item.type, item]));

export const LEGACY_WIDGET_TYPE_ALIASES: Readonly<Record<string, string>> = {
  lamp: "state_indicator",
  bool_display: "state_indicator",
  status_badge: "data_status",
  write_button: "command_button",
};

export const SOURCE_WIDGET_MIGRATIONS: Readonly<Record<string, string>> = {
  "Prostokąt": "shape",
  "Obraz": "image",
  "Bit Lamp": "state_indicator",
  WordLamp: "state_indicator",
  "Set Bit button": "command_button",
  "Set Rejgister button": "command_button",
  "Function button": "command_button",
  Suwak: "numeric_input",
  "Display register": "numeric",
  Chart: "trend",
  QRCode: "qr_code",
  CheckBox: "boolean_input",
  ComboBox: "select_input",
  Chips: "select_input",
  Collapse: "disclosure_panel",
  DataGrid: "collection_view",
  Dialog: "dialog",
  Switch: "boolean_input",
  TextField: "text_input",
  Link: "navigation_link",
  List: "collection_view",
  "Simple table": "collection_view",
  Tabs: "tab_set",
  TimeLine: "event_timeline",
  BarGraph: "meter",
  Alert: "notification",
  MessageBox: "dialog",
  NavMenu: "navigation_menu",
  Progress: "meter",
  Snackbar: "notification",
  Tooltip: "tooltip",
  "Embeded screen": "embedded_screen",
  "Alarm Panel": "alarm_panel",
};

export function getWidgetCatalogItem(type: string): WidgetCatalogItem | undefined {
  return WIDGET_CATALOG_BY_TYPE.get(type) ??
    WIDGET_CATALOG_BY_TYPE.get(LEGACY_WIDGET_TYPE_ALIASES[type] ?? "");
}

function validateCatalog(): void {
  const types = new Set<string>();
  const ids = new Set<string>();
  for (const item of WIDGET_CATALOG) {
    if (types.has(item.type)) throw new Error(`Duplicate widget type: ${item.type}`);
    if (ids.has(item.canonicalId)) throw new Error(`Duplicate widget canonicalId: ${item.canonicalId}`);
    if (!TOOLBOX_CATEGORIES.includes(item.category)) {
      throw new Error(`Unknown widget category for ${item.type}: ${item.category}`);
    }
    if (item.defaultW <= 0 || item.defaultH <= 0) {
      throw new Error(`Invalid default geometry for ${item.type}`);
    }
    types.add(item.type);
    ids.add(item.canonicalId);
  }

  const missingCanonical = CANONICAL_WIDGET_IDS.filter((id) => !ids.has(id));
  const extraCanonical = CANONICAL_WIDGETS.filter(
    (item) => !CANONICAL_WIDGET_IDS.includes(item.canonicalId as CanonicalWidgetId),
  );
  if (missingCanonical.length > 0 || extraCanonical.length > 0 || CANONICAL_WIDGETS.length !== 35) {
    throw new Error(
      `Canonical widget catalog mismatch; missing=${missingCanonical.join(",")}; extra=${extraCanonical
        .map((item) => item.canonicalId)
        .join(",")}; count=${CANONICAL_WIDGETS.length}`,
    );
  }
  const sourceMigrations = Object.entries(SOURCE_WIDGET_MIGRATIONS);
  if (sourceMigrations.length !== 33) {
    throw new Error(`Expected 33 source widget migrations, got ${sourceMigrations.length}`);
  }
  for (const [source, target] of sourceMigrations) {
    if (!WIDGET_CATALOG_BY_TYPE.has(target)) {
      throw new Error(`Source widget migration ${source} targets missing type ${target}`);
    }
  }
}

validateCatalog();
