import type { TagDefinition, TagValue, Role } from "$lib/types";

export const SYSTEM_DEVICE_ID = "SYS_INTERNAL";

/** Predefined SCADA System Internal Tags. */
export const SYSTEM_TAG_DEFINITIONS: TagDefinition[] = [
  {
    id: "SYS.Time",
    name: "Czas Systemowy (HH:MM:SS)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 0, table: "system", writable: false, string_length: 12 },
    unit: "",
    description: "Aktualny czas systemowy w formacie HH:MM:SS",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Date",
    name: "Data Systemowa (YYYY-MM-DD)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 1, table: "system", writable: false, string_length: 12 },
    unit: "",
    description: "Aktualna data systemowa w formacie YYYY-MM-DD",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.DateTime",
    name: "Data i Czas (YYYY-MM-DD HH:MM:SS)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 2, table: "system", writable: false, string_length: 24 },
    unit: "",
    description: "Pełny znacznik czasu systemowego",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Hour",
    name: "Godzina (0..23)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "u16",
    binding: { address: 3, table: "system", writable: false },
    unit: "h",
    description: "Bieżąca godzina 0..23",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Minute",
    name: "Minuta (0..59)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "u16",
    binding: { address: 4, table: "system", writable: false },
    unit: "min",
    description: "Bieżąca minuta 0..59",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Second",
    name: "Sekunda (0..59)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "u16",
    binding: { address: 5, table: "system", writable: false },
    unit: "s",
    description: "Bieżąca sekunda 0..59",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.SystemName",
    name: "Nazwa Systemu SCADA",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 6, table: "system", writable: false, string_length: 32 },
    unit: "",
    description: "Identyfikator stacji inżynieryjnej ProScada",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Version",
    name: "Wersja Oprogramowania",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 7, table: "system", writable: false, string_length: 20 },
    unit: "",
    description: "Wersja silnika ProScada Runtime",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.DiskFreeMB",
    name: "Wolne Miejsce na Dysku",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "u32",
    binding: { address: 8, table: "system", writable: false },
    unit: "MB",
    description: "Dostępne wolne miejsce na dysku systemowym w MB",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.CpuUsagePct",
    name: "Zużycie Procesora Engine",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "f32",
    binding: { address: 9, table: "system", writable: false },
    unit: "%",
    description: "Estymowane obciążenie cyklu silnika SCADA",
    scale: 1,
    offset: 0,
    decimals: 1,
    is_system: true,
  },
  {
    id: "SYS.UptimeSec",
    name: "Czas Pracy Silnika (Uptime)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "u32",
    binding: { address: 10, table: "system", writable: false },
    unit: "s",
    description: "Czas ciągłej pracy silnika SCADA w sekundach",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Mode",
    name: "Tryb Aplikacji (Designer/Runtime)",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 11, table: "system", writable: false, string_length: 16 },
    unit: "",
    description: "Aktualny tryb pracy oprogramowania ProScada",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Role",
    name: "Rola Użytkownika",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "string",
    binding: { address: 12, table: "system", writable: false, string_length: 16 },
    unit: "",
    description: "Uprawnienia aktywnego operatora",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.Connected",
    name: "Połączenie ze Sterownikiem PLC",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "bool",
    binding: { address: 13, table: "system", writable: false },
    unit: "",
    description: "Status komunikacji cyklicznej PLC (1 = OK, 0 = Offline)",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
  {
    id: "SYS.PollCount",
    name: "Licznik Cykli Odpytywania",
    device_id: SYSTEM_DEVICE_ID,
    data_type: "u32",
    binding: { address: 14, table: "system", writable: false },
    unit: "cykli",
    description: "Liczba wykonanych cykli Modbus TCP",
    scale: 1,
    offset: 0,
    decimals: 0,
    is_system: true,
  },
];

const startTime = Date.now();

export interface SystemSnapshotContext {
  connected?: boolean;
  pollCount?: number;
  mode?: string;
  role?: Role;
}

/**
 * Computes live SCADA system tag values based on current time and engine state.
 */
export function computeSystemTagValues(ctx?: SystemSnapshotContext): TagValue[] {
  const now = new Date();
  const uptimeSec = Math.floor((Date.now() - startTime) / 1000);
  const nowIso = now.toISOString();

  const pad2 = (n: number) => String(n).padStart(2, "0");
  const timeStr = `${pad2(now.getHours())}:${pad2(now.getMinutes())}:${pad2(now.getSeconds())}`;
  const dateStr = `${now.getFullYear()}-${pad2(now.getMonth() + 1)}-${pad2(now.getDate())}`;
  const dateTimeStr = `${dateStr} ${timeStr}`;

  // Estimate free disk space or mock
  const freeDiskMb = 148500 + (now.getSeconds() % 10) * 12;
  const cpuPct = 1.2 + (now.getSeconds() % 5) * 0.4;

  const modeStr = ctx?.mode === "runtime" ? "Runtime" : "Designer";
  const roleStr = ctx?.role ? ctx.role.toUpperCase() : "ENGINEER";
  const isConn = ctx?.connected ?? false;
  const pollCnt = ctx?.pollCount ?? 0;

  return [
    {
      tag_id: "SYS.Time",
      value: now.getHours() * 3600 + now.getMinutes() * 60 + now.getSeconds(),
      bool_value: false,
      string_value: timeStr,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: 0,
    },
    {
      tag_id: "SYS.Date",
      value: now.getFullYear(),
      bool_value: false,
      string_value: dateStr,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: 0,
    },
    {
      tag_id: "SYS.DateTime",
      value: Math.floor(now.getTime() / 1000),
      bool_value: false,
      string_value: dateTimeStr,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: 0,
    },
    {
      tag_id: "SYS.Hour",
      value: now.getHours(),
      bool_value: false,
      string_value: String(now.getHours()),
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: now.getHours(),
    },
    {
      tag_id: "SYS.Minute",
      value: now.getMinutes(),
      bool_value: false,
      string_value: String(now.getMinutes()),
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: now.getMinutes(),
    },
    {
      tag_id: "SYS.Second",
      value: now.getSeconds(),
      bool_value: false,
      string_value: String(now.getSeconds()),
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: now.getSeconds(),
    },
    {
      tag_id: "SYS.SystemName",
      value: 1,
      bool_value: true,
      string_value: "ProScada Workstation",
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: 1,
    },
    {
      tag_id: "SYS.Version",
      value: 1.0,
      bool_value: true,
      string_value: "v1.0.0 ProScada",
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: 1,
    },
    {
      tag_id: "SYS.DiskFreeMB",
      value: freeDiskMb,
      bool_value: true,
      string_value: `${freeDiskMb} MB`,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: freeDiskMb,
    },
    {
      tag_id: "SYS.CpuUsagePct",
      value: Number(cpuPct.toFixed(1)),
      bool_value: true,
      string_value: `${cpuPct.toFixed(1)}%`,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: cpuPct,
    },
    {
      tag_id: "SYS.UptimeSec",
      value: uptimeSec,
      bool_value: true,
      string_value: `${uptimeSec}s`,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: uptimeSec,
    },
    {
      tag_id: "SYS.Mode",
      value: ctx?.mode === "runtime" ? 1 : 0,
      bool_value: ctx?.mode === "runtime",
      string_value: modeStr,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: ctx?.mode === "runtime" ? 1 : 0,
    },
    {
      tag_id: "SYS.Role",
      value: 1,
      bool_value: true,
      string_value: roleStr,
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: 1,
    },
    {
      tag_id: "SYS.Connected",
      value: isConn ? 1 : 0,
      bool_value: isConn,
      string_value: isConn ? "Connected" : "Disconnected",
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: isConn ? 1 : 0,
    },
    {
      tag_id: "SYS.PollCount",
      value: pollCnt,
      bool_value: pollCnt > 0,
      string_value: String(pollCnt),
      quality: "good",
      ts: nowIso,
      age_ms: 10,
      raw: pollCnt,
    },
  ];
}

export function isSystemTag(tagId: string): boolean {
  return tagId.startsWith("SYS.") || SYSTEM_TAG_DEFINITIONS.some((t) => t.id === tagId);
}
